#!/bin/csh

set semester=21fall
set course=401_601
set assignment=cfg

#
# THE REST OF THE FILE SHOULD REMAIN UNCHANGED
#

/home/turing/karonis/Classes/ForStudents/submit $semester $user $assignment $1 $course
